---
title: "gitStarted"
author: "Emily Bean"
date: "December 24, 2019"
output: html_document
---

# Git Started with Github  

**Version control SOP for Ganda Lab, Penn State University**  

### Basics  

Git is a system of version control. Version control allows our lab to collaborate in a controlled way; this means that if someone makes a mistake, we can "unwind" it. We can also collaborate on code and share files. We can also store raw data and code for published projects in a permanent repository.  

A *repository* is a virtual filing cabinet. The repository stores folders and files. There is one general `ganda-lab` repository to store lab protocols, working data, script tutorials, etc. Each stand-alone project should have its own repository.  
Generally, each repository has one owner that controls the version control for the files in that repository. To make the collaborative process more efficient, we have *branches*. Branches are copies of the repository where an individual can make changes, add stuff, delete stuff - whatever - without changing the original `master branch`. The master branch stores the "working" repository.  

Collaborators need to use branches for effective version control. There are two ways to gain access to someone else's repository: you can `clone` the repository or `fork` the respository. *Cloning* creates a static copy of the repository that is locally downloaded. This is a great way to download software from Github, since you can still pull master changes (more on this below). However, it is difficult to collaborate from a cloned repository. *Forking* creates a forked branch of the repository that is locally downloaded. From there, you can make changes and submit a *merge request* to push those changes back to the master branch.
